// add employee data
export const CREATE_EMPLOYEE_DATA_START="CREATE_EMPLOYEE_DATA_START"
export const CREATE_EMPLOYEE_DATA_SUCCESS="CREATE_EMPLOYEE_DATA_SUCCESS"
export const CREATE_EMPLOYEE_DATA_ERROR="CREATE_EMPLOYEE_DATA_ERROR"

// get employee data
export const LOAD_EMPLOYEE_DATA_START="LOAD_EMPLOYEE_DATA_START"
export const LOAD_EMPLOYEE_DATA_SUCCESS="LOAD_EMPLOYEE_DATA_SUCCESS"
export const LOAD_EMPLOYEE_DATA_ERROR="LOAD_EMPLOYEE_DATA_ERROR"


// delete employee data
export const DELETE_EMPLOYEE_DATA_START="DELETE_EMPLOYEE_DATA_START"
export const DELETE_EMPLOYEE_DATA_SUCCESS="DELETE_EMPLOYEE_DATA_SUCCESS"
export const DELETE_EMPLOYEE_DATA_ERROR="DELETE_EMPLOYEE_DATA_ERROR"
// update employee data
export const UPDATE_EMPLOYEE_DATA_START="UPDATE_EMPLOYEE_DATA_START"
export const UPDATE_EMPLOYEE_DATA_SUCCESS="UPDATE_EMPLOYEE_DATA_SUCCESS"
export const UPDATE_EMPLOYEE_DATA_ERROR="UPDATE_EMPLOYEE_DATA_ERROR"
// add leave data
export const CREATE_LEAVE_DATA_START = "CREATE_LEAVE_DATA_START";
export const CREATE_LEAVE_DATA_SUCCESS = "CREATE_LEAVE_DATA_SUCCESS";
export const CREATE_LEAVE_DATA_ERROR = "CREATE_LEAVE_DATA_ERROR";

// get leave data
export const LOAD_LEAVE_DATA_START = "LOAD_LEAVE_DATA_START";
export const LOAD_LEAVE_DATA_SUCCESS = "LOAD_LEAVE_DATA_SUCCESS";
export const LOAD_LEAVE_DATA_ERROR = "LOAD_LEAVE_DATA_ERROR";


// update leave data 
export const UPDATE_LEAVE_DATA_START = "UPDATE_LEAVE_DATA_START";
export const UPDATE_LEAVE_DATA_SUCCESS = "UPDATE_LEAVE_DATA_SUCCESS";
export const UPDATE_LEAVE_DATA_ERROR = "UPDATE_LEAVE_DATA_ERROR";

// delete leave data
export const DELETE_LEAVE_DATA_START="DELETE_LEAVE_DATA_START"
export const DELETE_LEAVE_DATA_SUCCESS="DELETE_LEAVE_DATA_SUCCESS"
export const DELETE_LEAVE_DATA_ERROR="DELETE_LEAVE_DATA_ERROR"

//authentation data
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";